version: '3.7'

networks:
    books:
        name: books-external

services:
    read-db:
        image: mongo:latest
        networks:
            - books
        volumes:
            - "../../:/app"
            - "./initdb.d:/docker-entrypoint-initdb.d"
        environment:
            MONGO_INITDB_ROOT_USERNAME: readbooks
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: readbooks
    read-ms:
        build:
            context: ../..
            dockerfile: ./docker/development/Dockerfile
        volumes:
            - ../../:/app
        networks:
            - books
        environment:
            DATABASE_URI: mongodb://user:secret@read-db/readbooks
        working_dir: /app
        ports:
            - 8890:8890
        command: '/app/tools/run-backend.sh'
        depends_on:
            - read-db
